### PR TITLE
Show convert_options in README

### PR DESCRIPTION
**Pull request by erkie**
I spent some time searching for how to add custom command line options, and had to spend a while in the source code of a couple of projects to understand the correct format of things. So I added it to the readme.

### CODE REVIEW

**Comment by wataori** [comment]
Yeah I'm just about to add it on my fork. :+1: 
I also spent time for searching to add "-vf scale=640:-1" option.

**Comment by erkie** [comment]
@wataori awesome. What additional changes are you working on? @owahab seems to need help to move these projects forward.

**Comment by wataori** [comment]
@erkie No. I think it's enough but unfortunately CI has failed.

**Comment by owahab** [comment]
Travis fails due to APT packages.

**Pull request merged**
